# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85e66c3c9fc8456458a90bdac7072cbf21c583645075777e16a21a216ef1848f2b5d90921d0b080854780a8129f28f049b8c2d013128b58e13af3818ae78290a

test:
  secret_key_base: 0cf3b36b7947c3c027cf667a2ed48e3ecfa06f3b7994f24c339727dd2b2d0a33d25985a4a2e35e793160d37c717e4ae7578a6f8475be761483d8867f44ab03aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
